
 export const regions = [
    "전국", "서울", "인천", "부산", "광주광역시", "대전", "대구", "세종", "울산", "경기", "강원", "충청북도", "충청남도", "전라북도", "전라남도", "경상북도", "경상남도", "제주"
  ];
  
 


  export const hierarchicalRegions = [
    { region: "서울", subRegions: ["강남구", "강동구", "강북구", "강서구", "관악구", "광진구", "구로구", "금천구", "노원구", "도봉구", "동대문구", "동작구", "마포구", "서대문구", "서초구", "성동구", "성북구", "송파구", "양천구", "영등포구", "용산구", "은평구", "종로구", "중구", "중랑구"] },
    { region: "부산", subRegions: ["강서구", "금정구", "기장군", "남구", "동구", "동래구", "진구", "북구", "사상구", "사하구", "서구", "수영구", "연제구", "영도구", "중구", "해운대구"] },
    { region: "대구", subRegions: ["남구", "달서구", "달성군", "동구", "북구", "서구", "수성구", "중구"] },
    { region: "인천", subRegions: ["강화군", "계양구", "남동구", "동구", "미추홀구", "부평구", "서구", "연수구", "옹진군", "중구"] },
    { region: "광주", subRegions: ["광산구", "남구", "동구", "북구", "서구"] }, // UI는 '광주', API는 '광주광역시'
    { region: "대전", subRegions: ["대덕구", "동구", "서구", "유성구", "중구"] },
    { region: "울산", subRegions: ["남구", "동구", "북구", "울주군", "중구"] },
    { region: "세종시", subRegions: ["세종특별자치시"] }, // API는 '세종시'로 인식할 가능성 (확인 필요)
    { region: "경기", subRegions: ["가평군", "고양시", "과천시", "광명시", "광주시", "구리시", "군포시", "김포시", "남양주시", "동두천시", "부천시", "성남시", "수원시", "시흥시", "안산시", "안성시", "안양시", "양주시", "양평군", "여주시", "연천군", "오산시", "용인시", "의왕시", "의정부시", "이천시", "파주시", "평택시", "포천시", "하남시", "화성시"] },
    { region: "강원", subRegions: ["강릉시", "고성군", "동해시", "삼척시", "속초시", "양구군", "양양군", "영월군", "원주시", "인제군", "정선군", "철원군", "춘천시", "태백시", "평창군", "홍천군", "화천군", "횡성군"] },
    { region: "충북", subRegions: ["괴산군", "단양군", "보은군", "영동군", "옥천군", "음성군", "제천시", "증평군", "진천군", "청주시", "충주시"] }, // UI는 '충북', API는 '충청북도'
    { region: "충남", subRegions: ["계룡시", "공주시", "금산군", "논산시", "당진시", "보령시", "부여군", "서산시", "서천군", "아산시", "예산군", "천안시", "청양군", "태안군", "홍성군"] }, // UI는 '충남', API는 '충청남도'
    { region: "전북", subRegions: ["고창군", "군산시", "김제시", "남원시", "무주군", "부안군", "순창군", "익산시", "임실군", "장수군", "전주시", "정읍시", "진안군"] }, // UI는 '전북', API는 '전라북도'
    { region: "전남", subRegions: ["강진군", "고흥군", "곡성군", "광양시", "구례군", "나주시", "담양군", "목포시", "무안군", "보성군", "순천시", "신안군", "여수시", "영광군", "영암군", "완도군", "장성군", "장흥군", "진도군", "함평군", "해남군", "화순군"] }, // UI는 '전남', API는 '전라남도'
    { region: "경북", subRegions: ["경산시", "경주시", "고령군", "구미시", "군위군", "김천시", "문경시", "봉화군", "상주시", "성주군", "안동시", "영덕군", "영양군", "영주시", "영천시", "예천군", "울릉군", "울진군", "의성군", "청도군", "청송군", "칠곡군", "포항시"] }, // UI는 '경북', API는 '경상북도'
    { region: "경남", subRegions: ["거제시", "거창군", "고성군", "김해시", "남해군", "밀양시", "사천시", "산청군", "양산시", "의령군", "진주시", "창녕군", "창원시", "통영시", "하동군", "함안군", "함양군", "함천군"] }, // UI는 '경남', API는 '경상남도'
    { region: "제주", subRegions: ["서귀포시", "제주시"] },
  ];


 export const countries = [
  { value: "AF", label: "Afghanistan(아프가니스탄)" },
  { value: "AL", label: "Albania(알바니아)" },
  { value: "DZ", label: "Algeria(알제리)" },
  { value: "AD", label: "Andorra(안도라)" },
  { value: "AO", label: "Angola(앙골라)" },
  { value: "AG", label: "Antigua and Barbuda(앤티가바부다)" },
  { value: "AR", label: "Argentina(아르헨티나)" },
  { value: "AM", label: "Armenia(아르메니아)" },
  { value: "AU", label: "Australia(호주)" },
  { value: "AT", label: "Austria(오스트리아)" },
  { value: "AZ", label: "Azerbaijan(아제르바이잔)" },
  { value: "BS", label: "Bahamas(바하마)" },
  { value: "BH", label: "Bahrain(바레인)" },
  { value: "BD", label: "Bangladesh(방글라데시)" },
  { value: "BB", label: "Barbados(바베이도스)" },
  { value: "BY", label: "Belarus(벨라루스)" },
  { value: "BE", label: "Belgium(벨기에)" },
  { value: "BZ", label: "Belize(벨리즈)" },
  { value: "BJ", label: "Benin(베냉)" },
  { value: "BT", label: "Bhutan(부탄)" },
  { value: "BO", label: "Bolivia(볼리비아)" },
  { value: "BA", label: "Bosnia-Herzegovina(보스니아헤르체고비나)" },
  { value: "BW", label: "Botswana(보츠와나)" },
  { value: "BR", label: "Brazil(브라질)" },
  { value: "BN", label: "Brunei(브루나이)" },
  { value: "BG", label: "Bulgaria(불가리아)" },
  { value: "BF", label: "Burkina Faso(부르키나파소)" },
  { value: "BI", label: "Burundi(부룬디)" },
  { value: "KH", label: "Cambodia(캄보디아)" },
  { value: "CM", label: "Cameroon(카메룬)" },
  { value: "CA", label: "Canada(캐나다)" },
  { value: "CV", label: "Cape Verde(카보베르데)" },
  { value: "CF", label: "Central African Republic(중앙아프리카공화국)" },
  { value: "TD", label: "Chad(차드)" },
  { value: "CL", label: "Chile(칠레)" },
  { value: "CN", label: "China(중국)" },
  { value: "CO", label: "Colombia(콜롬비아)" },
  { value: "KM", label: "Comoros(코모로)" },
  { value: "CG", label: "Congo(콩고공화국)" },
  { value: "CK", label: "Cook Islands(쿡제도)" },
  { value: "CR", label: "Costa Rica(코스타리카)" },
  { value: "CI", label: "Cote d'Ivoire(코트디부아르)" },
  { value: "HR", label: "Croatia(크로아티아)" },
  { value: "CU", label: "Cuba(쿠바)" },
  { value: "CY", label: "Cyprus(사이프러스)" },
  { value: "CZ", label: "Czech(체코)" },
  { value: "CD", label: "Democratic Republic of Congo(콩고민주공화국(DR콩고))" },
  { value: "DK", label: "Denmark(덴마크)" },
  { value: "DJ", label: "Djibouti(지부티)" },
  { value: "DM", label: "Dominica(도미니카연방)" },
  { value: "DO", label: "Dominican Republic(도미니카공화국)" },
  { value: "EC", label: "Ecuador(에콰도르)" },
  { value: "EG", label: "Egypt(이집트)" },
  { value: "SV", label: "El Salvador(엘살바도르)" },
  { value: "GQ", label: "Equatorial Guinea(적도기니)" },
  { value: "ER", label: "Eritrea(에리트레아)" },
  { value: "EE", label: "Estonia(에스토니아)" },
  { value: "SZ", label: "Eswatini(에스와티니)" },
  { value: "ET", label: "Ethiopia(에티오피아)" },
  { value: "FM", label: "Federated States of Micronesia(마이크로네시아연방)" },
  { value: "FJ", label: "Fiji(피지)" },
  { value: "FI", label: "Finland(핀란드)" },
  { value: "FR", label: "France(프랑스)" },
  { value: "GA", label: "Gabon(가봉)" },
  { value: "GM", label: "Gambia(감비아)" },
  { value: "GE", label: "Georgia(조지아)" },
  { value: "DE", label: "Germany(독일)" },
  { value: "GH", label: "Ghana(가나)" },
  { value: "GR", label: "Greece(그리스)" },
  { value: "GD", label: "Grenada(그레나다)" },
  { value: "GT", label: "Guatemala(과테말라)" },
  { value: "GN", label: "Guinea(기니)" },
  { value: "GW", label: "Guinea-Bissau(기니비사우)" },
  { value: "GY", label: "Guyana(가이아나)" },
  { value: "HT", label: "Haiti(아이티)" },
  { value: "HN", label: "Honduras(온두라스)" },
  { value: "HK", label: "Hong Kong(홍콩)" },
  { value: "HU", label: "Hungary(헝가리)" },
  { value: "IS", label: "Iceland(아이슬란드)" },
  { value: "IN", label: "India(인도)" },
  { value: "ID", label: "Indonesia(인도네시아)" },
  { value: "IR", label: "Iran(이란)" },
  { value: "IQ", label: "Iraq(이라크)" },
  { value: "IE", label: "Ireland(아일랜드)" },
  { value: "IL", label: "Israel(이스라엘)" },
  { value: "IT", label: "Italia(이탈리아)" },
  { value: "JM", label: "Jamaica(자메이카)" },
  { value: "JP", label: "Japan(일본)" },
  { value: "JO", label: "Jordan(요르단)" },
  { value: "KZ", label: "Kazakhstan(카자흐스탄)" },
  { value: "KE", label: "Kenya(케냐)" },
  { value: "KI", label: "Kiribati(키리바시)" },
  { value: "XK", label: "Kosovo(코소보)" },
  { value: "KW", label: "Kuwait(쿠웨이트)" },
  { value: "KG", label: "Kyrgyz(키르기즈)" },
  { value: "LA", label: "Laos(라오스)" },
  { value: "LV", label: "Latvia(라트비아)" },
  { value: "LB", label: "Lebanon(레바논)" },
  { value: "LS", label: "Lesotho(레소토)" },
  { value: "LR", label: "Liberia(라이베리아)" },
  { value: "LY", label: "Libya(리비아)" },
  { value: "LI", label: "Liechtenstein(리히텐슈타인)" },
  { value: "LT", label: "Lithuania(리투아니아)" },
  { value: "LU", label: "Luxembourg(룩셈부르크)" },
  { value: "MG", label: "Madagascar(마다가스카르)" },
  { value: "MW", label: "Malawi(말라위)" },
  { value: "MY", label: "Malaysia(말레이시아)" },
  { value: "MV", label: "Maldives(몰디브)" },
  { value: "ML", label: "Mali(말리)" },
  { value: "MT", label: "Malta(몰타)" },
  { value: "MH", label: "Marshall Islands(마셜제도)" },
  { value: "MR", label: "Mauritania(모리타니아)" },
  { value: "MU", label: "Mauritius(모리셔스)" },
  { value: "MZ", label: "Mazambique(모잠비크)" },
  { value: "MX", label: "Mexico(멕시코)" },
  { value: "MD", label: "Moldova(몰도바)" },
  { value: "MC", label: "Monaco(모나코)" },
  { value: "MN", label: "Mongolia(몽골)" },
  { value: "ME", label: "Montenegro(몬테네그로)" },
  { value: "MA", label: "Morocco(모로코)" },
  { value: "MM", label: "Myanmar(미얀마)" },
  { value: "NA", label: "Namibia(나미비아)" },
  { value: "NR", label: "Nauru(나우루)" },
  { value: "NP", label: "Nepal(네팔)" },
  { value: "NL", label: "Netherlands(네덜란드)" },
  { value: "NZ", label: "New Zealand(뉴질랜드)" },
  { value: "NI", label: "Nicaragua(니카라과)" },
  { value: "NE", label: "Niger(니제르)" },
  { value: "NG", label: "Nigeria(나이지리아)" },
  { value: "NU", label: "Niue(니우에)" },
  { value: "MK", label: "North Macedonia(북마케도니아)" },
  { value: "NO", label: "Norway(노르웨이)" },
  { value: "OM", label: "Oman(오만)" },
  { value: "PK", label: "Pakistan(파키스탄)" },
  { value: "PW", label: "Palau(팔라우)" },
  { value: "PS", label: "Palestine(팔레스타인)" },
  { value: "PA", label: "Panama(파나마)" },
  { value: "PG", label: "Papua New Guinea(파푸아뉴기니)" },
  { value: "PY", label: "Paraguay(파라과이)" },
  { value: "PE", label: "Peru(페루)" },
  { value: "PH", label: "Philippines(필리핀)" },
  { value: "PL", label: "Poland(폴란드)" },
  { value: "PT", label: "Portugal(포르투갈)" },
  { value: "QA", label: "Qatar(카타르)" },
  { value: "TR", label: "Republic of Turkiye(튀르키예공화국)" },
  { value: "RO", label: "Romania(루마니아)" },
  { value: "RU", label: "Russia(러시아)" },
  { value: "RW", label: "Rwanda(르완다)" },
  { value: "WS", label: "Samoa(사모아)" },
  { value: "SM", label: "San Marino(산마리노)" },
  { value: "ST", label: "Sao Tome e Principe(상투메프린시페)" },
  { value: "SA", label: "Saudi Arabia(사우디아라비아)" },
  { value: "SN", label: "Senegal(세네갈)" },
  { value: "RS", label: "Serbia(세르비아)" },
  { value: "SC", label: "Seychelles(세이셸)" },
  { value: "SL", label: "Sierra Leone(시에라리온)" },
  { value: "SG", label: "Singapore(싱가포르)" },
  { value: "SK", label: "Slovakia(슬로바키아)" },
  { value: "SI", label: "Slovenia(슬로베니아)" },
  { value: "SB", label: "Solomon Islands(솔로몬제도)" },
  { value: "SO", label: "Somalia(소말리아)" },
  { value: "ZA", label: "South Africa(남아프리카공화국)" },
  { value: "SS", label: "South Sudan(남수단)" },
  { value: "ES", label: "Spain(스페인)" },
  { value: "LK", label: "Sri Lanka(스리랑카)" },
  { value: "KN", label: "St. Kitts-Nevis(세인트 키츠 네비스)" },
  { value: "LC", label: "St. Lucia(세인트 루시아)" },
  { value: "VC", label: "St. Vincent & the Grenadines(세인트 빈센트 그레나딘)" },
  { value: "SD", label: "Sudan(수단)" },
  { value: "SR", label: "Suriname(수리남)" },
  { value: "SE", label: "Sweden(스웨덴)" },
  { value: "CH", label: "Swiss(스위스)" },
  { value: "SY", label: "Syria(시리아)" },
  { value: "TW", label: "Taiwan(대만)" },
  { value: "TJ", label: "Tajikistan(타지키스탄)" },
  { value: "TZ", label: "Tanzania(탄자니아)" },
  { value: "TH", label: "Thailand(태국)" },
  { value: "TL", label: "Timor-Leste(동티모르)" },
  { value: "TG", label: "Togo(토고)" },
  { value: "TO", label: "Tonga(통가)" },
  { value: "TT", label: "Trinidad & Tobago(트리니다드토바고)" },
  { value: "TN", label: "Tunisia(튀니지)" },
  { value: "TM", label: "Turkmenistan(투르크메니스탄)" },
  { value: "TV", label: "Tuvalu(투발루)" },
  { value: "UG", label: "Uganda(우간다)" },
  { value: "UA", label: "Ukraine(우크라이나)" },
  { value: "AE", label: "United Arab Emirates(아랍에미리트)" },
  { value: "GB", label: "United Kingdom(영국)" },
  { value: "US", label: "United States of America(미국)" },
  { value: "UY", label: "Uruguay(우루과이)" },
  { value: "UZ", label: "Uzbekistan(우즈베키스탄)" },
  { value: "VU", label: "Vanuatu(바누아투)" },
  { value: "VA", label: "Vatican(교황청)" },
  { value: "VE", label: "Venezuela(베네수엘라)" },
  { value: "VN", label: "Vietnam(베트남)" },
  { value: "YE", label: "Yemen(예멘)" },
  { value: "ZM", label: "Zambia(잠비아)" },
  { value: "ZW", label: "Zimbabwe(짐바브웨)" },
];

export const visas = [
  { value: "0-1", label: "취득예정" },
  { value: "C-4", label: "C-4 단기취업" },
  { value: "D-2", label: "D-2 유학" },
  { value: "D-4", label: "D-4 일반연수" },
  { value: "D-5", label: "D-5 취재" },
  { value: "D-7", label: "D-7 주재" },
  { value: "D-8", label: "D-8 기업투자" },
  { value: "D-10", label: "D-10 구직" },
  { value: "E-1", label: "E-1 교수" },
  { value: "E-2", label: "E-2 회화지도" },
  { value: "E-3", label: "E-3 연구" },
  { value: "E-4", label: "E-4 기술지도" },
  { value: "E-5", label: "E-5 전문직업" },
  { value: "E-6", label: "E-6 예술흥행" },
  { value: "E-7", label: "E-7 특정활동" },
  { value: "E-8", label: "E-8 계절근로" },
  { value: "E-9", label: "E-9 비전문취업" },
  { value: "E-10", label: "E-10 선원취업" },
  { value: "F-1", label: "F-1 방문동거" },
  { value: "F-2", label: "F-2 거주" },
  { value: "F-3", label: "F-3 동반가족" },
  { value: "F-4", label: "F-4 재외동포" },
  { value: "F-5", label: "F-5 영주" },
  { value: "F-6", label: "F-6 결혼이민" },
  { value: "G-1", label: "G-1 기타" },
  { value: "H-1", label: "H-1 관광취업" },
  { value: "H-2", label: "H-2 방문취업" },
];